name: Publish image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id:   docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile
          tags: |
            paritytech/evm-tps:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
